using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using UnityEngine;

namespace Ateo.Build
{
	/// <summary>
	/// Turns the Unity-generated Xcode project (<see cref="ArtifactKind.XcodeProject"/>) into a signed
	/// <see cref="ArtifactKind.IPA"/> by driving fastlane (read-only <c>match</c> consume + <c>build_app</c>)
	/// through a TRANSIENT Fastfile the action writes itself - a faithful copy of the shared <c>ios build_ipa</c>
	/// lane in build-agent-scripts/fastlane/Fastfile. Self-contained on purpose (§10 local parity): that CI lane
	/// exists only in the build-agent-scripts checkout, so invoking it made a LOCAL panel build die with "Could
	/// not find Fastfile"; generating the identical lane under a temp dir gives server and local builds the same
	/// behavior with no external checkout. macOS + Xcode + fastlane + git only. Signing inputs (team +
	/// provisioning profile) come from the definition's <see cref="iOSBuildDefinition.Signing"/>; the match repo
	/// coordinates are committed author settings (the repo itself is encrypted); the match passphrase arrives as
	/// a resolved secret, never from the committed asset. No App Store Connect API key: the lane makes no Apple
	/// API call (match is a read-only git consume), so none is declared or resolved.
	/// </summary>
	[System.Serializable]
	public sealed class BuildIPA : PostBuildAction<iOSBuildDefinition>
	{
		#region Constants

		private const string MatchPasswordKey = "MATCH_PASSWORD";

		/// <summary>
		/// The transient lane, written to &lt;temp&gt;/fastlane/Fastfile and run from &lt;temp&gt;. Kept as close
		/// to the CI lane (build-agent-scripts/fastlane/Fastfile, "ios build_ipa") as possible so the two stay
		/// behaviorally identical - if you change one, change the other. Two deliberate deviations:
		/// (1) match gets its git coordinates from MATCH_GIT_URL / MATCH_GIT_BRANCH env instead of a Matchfile
		///     (the Matchfile also lives only in the CI checkout);
		/// (2) setup_ci only runs under CI=true - it REPLACES the default keychain with a temporary one, which is
		///     correct on a headless agent but hostile on a dev's own Mac, where the interactive session can
		///     simply answer the one-time keychain prompt instead.
		/// </summary>
		private const string FastfileTemplate =
@"# Transient Fastfile generated by the BuildIPA post-build action; deleted after the run.
# Mirrors build-agent-scripts/fastlane/Fastfile (lane 'ios build_ipa') - keep the two in sync.
require ""shellwords""

default_platform(:ios)

# EXPORT_METHOD (xcodebuild/plist spelling) -> match type (fastlane spelling)
MATCH_TYPE = {
  ""app-store""   => ""appstore"",
  ""ad-hoc""      => ""adhoc"",
  ""development"" => ""development"",
  ""enterprise""  => ""enterprise"",
}.freeze

platform :ios do
  desc ""Read-only match consume + xcodebuild archive/export -> signed .ipa""
  lane :build_ipa do
    bundle_id  = ENV.fetch(""BUNDLE_ID"")
    team_id    = ENV.fetch(""TEAM_ID"")
    profile    = ENV.fetch(""PROVISIONING_PROFILE"")
    method     = ENV.fetch(""EXPORT_METHOD"", ""app-store"")
    scheme     = ENV.fetch(""SCHEME"", ""Unity-iPhone"")
    xcode_dir  = ENV.fetch(""XCODE_DIR"")
    match_type = MATCH_TYPE.fetch(method) { UI.user_error!(""Unsupported EXPORT_METHOD: #{method}"") }
    # Unity bakes CODE_SIGN_IDENTITY=""iOS Development"" into the project, so xcodebuild looks for a
    # *development* cert and fails (we only hold the distribution cert). Force the distribution
    # identity for store/ad-hoc builds. Overridable via env for edge cases.
    code_sign_identity = ENV[""CODE_SIGN_IDENTITY""] ||
                         (match_type == ""development"" ? ""Apple Development"" : ""Apple Distribution"")

    # Temporary keychain + set-key-partition-list (non-interactive codesign). CI only: setup_ci swaps
    # the DEFAULT keychain for a temp one, which must not happen on a dev's own Mac (locally the
    # interactive session answers the one-time keychain prompt instead).
    setup_ci(force: true) if ENV[""CI""] == ""true""

    # Read-only consume: clone the encrypted repo, decrypt with MATCH_PASSWORD, install the shared
    # distribution cert + provisioning profile. Coordinates arrive via env (no Matchfile here).
    match(
      type: match_type,
      readonly: true,
      app_identifier: bundle_id,
      storage_mode: ""git"",
      git_url: ENV.fetch(""MATCH_GIT_URL""),
      git_branch: ENV.fetch(""MATCH_GIT_BRANCH"", ""main"")
    )

    # The Unity-generated Xcode project arrives at XCODE_DIR (absolute).
    podfile   = File.join(xcode_dir, ""Podfile"")
    workspace = File.join(xcode_dir, ""#{scheme}.xcworkspace"")
    project   = File.join(xcode_dir, ""#{scheme}.xcodeproj"")

    # CocoaPods is future-proofing; current Unity ports have no Podfile.
    cocoapods(podfile: podfile) if File.exist?(podfile)
    use_workspace = File.exist?(workspace)
    project_args  = use_workspace ? { workspace: workspace } : { project: project }

    # Pin the provisioning profile to the APP target ONLY. The Unity project has two targets: the app
    # (Unity-iPhone) and the embedded UnityFramework. A framework ""does not support provisioning
    # profiles"", so a GLOBAL PROVISIONING_PROFILE_SPECIFIER would fail the archive on the framework
    # target; per-target in the pbxproj scopes the profile to the app.
    update_code_signing_settings(
      path: project,
      use_automatic_signing: false,
      team_id: team_id,
      code_sign_identity: code_sign_identity,
      profile_name: profile,
      targets: [scheme]                    # app target == scheme name (Unity-iPhone)
    )

    build_app(
      **project_args,
      scheme: scheme,
      configuration: ""Release"",
      sdk: ""iphoneos"",
      clean: true,
      output_directory: File.join(xcode_dir, ""build"", ""ipa""),
      derived_data_path: File.join(xcode_dir, ""build"", ""DerivedData""),
      archive_path: File.join(xcode_dir, ""build"", ""App.xcarchive""),
      export_method: method,
      # Force manual signing + the distribution identity for ALL targets (overrides Unity's baked-in
      # ""iOS Development""). NO global PROVISIONING_PROFILE_SPECIFIER - the app target's profile is set
      # per-target above; the framework intentionally gets none.
      xcargs: ""CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=#{team_id} "" \
              ""CODE_SIGN_IDENTITY=#{code_sign_identity.shellescape}"",
      # skip_profile_detection: gym otherwise MERGES match's auto-detected profile mapping (which
      # includes the UnityFramework target) into the export plist -> export fails. With this true, the
      # export plist uses ONLY our explicit provisioningProfiles below (the app target alone).
      skip_profile_detection: true,
      export_options: {
        signingStyle: ""manual"",
        teamID: team_id,
        provisioningProfiles: { bundle_id => profile },
      }
    )
  end
end
";

		#endregion

		#region Fields

		[SerializeField, Tooltip("Xcode scheme to archive (Unity's app target; default 'Unity-iPhone').")]
		private string _scheme = "Unity-iPhone";

		[SerializeField, Tooltip("Export method: app-store, ad-hoc, development or enterprise.")]
		private string _exportMethod = "app-store";

		[SerializeField, Tooltip("App bundle identifier (e.g. com.ateo.game) - drives match + the export plist.")]
		private string _bundleId;

		[SerializeField, Tooltip("Git URL of the encrypted fastlane match signing repo (e.g. git@host:org/apple-signing.git). Safe to commit - the repo content is encrypted; access is your own git credential.")]
		private string _matchGitUrl;

		[SerializeField, Tooltip("Branch of the match repo holding this team's certs/profiles (branch-per-team). Default 'main'.")]
		private string _matchGitBranch = "main";

		#endregion

		#region Properties

		public override string DisplayName => "Build IPA (fastlane)";
		public override ArtifactKind Consumes => ArtifactKind.XcodeProject;
		public override ArtifactKind Produces => ArtifactKind.IPA;

		public override IEnumerable<SecretRequirement> RequiredSecrets => new[]
		{
			new SecretRequirement(MatchPasswordKey, "fastlane match repo passphrase.", SecretKind.String)
		};

		public override IEnumerable<HostRequirement> HostRequirements => new[]
		{
			HostRequirement.OS("macOS"),
			HostRequirement.Tool("xcodebuild"),
			HostRequirement.Tool("fastlane"),
			HostRequirement.Tool("git") // match clones the encrypted signing repo
		};

		#endregion

		#region Public Methods

		protected override async Task<ActionResult> ExecuteAsync(BuildContext ctx, iOSBuildDefinition def)
		{
			string xcodeDir = ActionProcess.PrimaryArtifact(ctx);
			if (string.IsNullOrEmpty(xcodeDir) || !Directory.Exists(xcodeDir))
			{
				return ActionResult.Fail("BuildIPA: no Xcode project folder to archive (artifact path '" + xcodeDir + "').");
			}

			// Fail-early on missing authoring inputs: the lane's ENV.fetch would also catch these, but a C#
			// message naming the Inspector field beats a Ruby KeyError buried in fastlane output.
			iOSSigning signing = def.Signing;
			if (string.IsNullOrEmpty(_bundleId))
			{
				return ActionResult.Fail("BuildIPA: 'Bundle Id' is not set on the action.");
			}

			if (!signing.IsConfigured)
			{
				return ActionResult.Fail("BuildIPA: the definition's iOS Signing ('Apple Team Id' + 'Provisioning Profile') is not configured.");
			}

			if (string.IsNullOrEmpty(_matchGitUrl))
			{
				return ActionResult.Fail("BuildIPA: 'Match Git Url' is not set on the action.");
			}

			string matchPassword = ctx.GetSecretString(MatchPasswordKey);

			// Hand the lane its inputs via env (same contract as the CI lane's ENV.fetch calls).
			Dictionary<string, string> env = new Dictionary<string, string>
			{
				// CI gates setup_ci in the lane: the temp-keychain swap belongs on the headless agent only.
				["CI"] = ctx.IsBatchMode ? "true" : "false",
				["XCODE_DIR"] = xcodeDir,
				["SCHEME"] = string.IsNullOrEmpty(_scheme) ? "Unity-iPhone" : _scheme,
				["EXPORT_METHOD"] = string.IsNullOrEmpty(_exportMethod) ? "app-store" : _exportMethod,
				["BUNDLE_ID"] = _bundleId,
				["TEAM_ID"] = signing.AppleTeamId ?? string.Empty,
				["PROVISIONING_PROFILE"] = signing.ProvisioningProfile ?? string.Empty,
				["MATCH_PASSWORD"] = matchPassword ?? string.Empty,
				["MATCH_GIT_URL"] = _matchGitUrl,
				["MATCH_GIT_BRANCH"] = string.IsNullOrEmpty(_matchGitBranch) ? "main" : _matchGitBranch
			};

			// Self-contained lane: fastlane resolves ./fastlane/Fastfile from its working directory, so the
			// transient copy is written under a temp dir and fastlane runs FROM there (all paths in the lane
			// are absolute via XCODE_DIR). Wiped in finally - nothing secret in it, but it must not accumulate.
			string laneRoot = Path.Combine(Path.GetTempPath(), "ateo-buildipa-" + Guid.NewGuid().ToString("N"));
			ActionProcess.ToolResult result;
			try
			{
				Directory.CreateDirectory(Path.Combine(laneRoot, "fastlane"));
				File.WriteAllText(Path.Combine(laneRoot, "fastlane", "Fastfile"), FastfileTemplate);

				ctx.Log?.Invoke("BuildIPA: fastlane match (readonly) + build_app (export=" + env["EXPORT_METHOD"] +
					", scheme=" + env["SCHEME"] + ")");

				result = await ActionProcess.RunAsync("fastlane", new[] { "ios", "build_ipa" }, laneRoot, env);
			}
			finally
			{
				try
				{
					if (Directory.Exists(laneRoot)) Directory.Delete(laneRoot, true);
				}
				catch (Exception)
				{
					// Best-effort: a leftover generated Fastfile in temp holds no secrets.
				}
			}

			if (!result.Succeeded)
			{
				return ActionResult.Fail("BuildIPA: fastlane exited " + result.ExitCode + ": " + result.Tail(20));
			}

			string ipaPath = ActionProcess.FindNewestFile(xcodeDir, "*.ipa")
				?? ActionProcess.FindNewestFile(ctx.BuildFolder, "*.ipa");
			if (string.IsNullOrEmpty(ipaPath))
			{
				return ActionResult.Fail("BuildIPA: fastlane succeeded but no .ipa was found under " + xcodeDir + ".");
			}

			ctx.ArtifactPaths.Add(ipaPath);

			ActionResult ok = ActionResult.Ok("built IPA " + Path.GetFileName(ipaPath));
			ok.Metadata["ipaPath"] = ipaPath;
			ok.Metadata["exportMethod"] = env["EXPORT_METHOD"];
			return ok;
		}

		#endregion
	}
}
